-- Drawable (add a type and get rid of sprite?)
-- Container (inventory for power ups)
-- Owner/Contained (inverse of container?)
-- Score
-- Size (instead of box?)
-- Ai (for monsters)
-- Power (for loot)
-- Health
-- Form
-- Monster (kind)
-- Flash
-- Particle
-- Label